### PR TITLE
Add Unicode license file for ucd-util/src/unicode_tables

### PR DESCRIPTION
**Pull request by kpozin**

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
Thanks!

**Comment by kpozin** [comment]
Thanks!

**Comment by kpozin** [comment]
@BurntSushi, when do you think you might be pushing the next release of this crate?

**Comment by BurntSushi** [comment]
Ah right sure. This PR is in `ucd-util 0.1.3` on crates.io.

**Pull request merged**
