### PR TITLE
Refactor: make ucd-generate available as a build dependency

### PR DESCRIPTION
**Pull request by addisoncrump**
[We depend on ucd-generate as a build dependency](https://github.com/AFLplusplus/LibAFL/blob/main/libafl/build.rs#L61-L65). Unfortunately, at this time we depend on the user to install ucd-generate.

This exposes the `run` function, accepting an iterator of command line arguments. Partially addresses #3.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Before I look at this, can you say why you don't just run this tool manually and commit the output?

**Comment by addisoncrump** [comment]
We have no reason to distribute unicode tables in most cases (this is a bonus feature), and we prefer to avoid inserting generated code into the git (it may frequently update with large diffs that aren't meaningful). We also provide very infrequent releases, and it is better for us to stay up to date rather than fixing to a specific version of Unicode.

**Comment by addisoncrump** [comment]
In practice, this turned out to be a bad idea :( Upstream is just not stable enough to guarantee we can always download the file.

**Comment by BurntSushi** [comment]
Yeah in my experience committing generated code to git is the least bad option IMO. I think the Debian people don't like this, but there is a lot of pain and effort required to make anything else work smoothly.

**Pull request closed without merging**
